bind 127.0.0.1
port 6379
daemonize no
loglevel notice
logfile ""
dir /app/data/redis
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 18mb
maxmemory 64mb
maxmemory-policy allkeys-lru
protected-mode no
maxclients 100
tcp-keepalive 300
